name: Build & Push Chamilo Docker Image
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push latest
        run: docker push ghcr.io/${{ github.repository }}:latest
      - name: Tag v2.0.3
        run: docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:v2.0.3
      - name: Push v2.0.3
        run: docker push ghcr.io/${{ github.repository }}:v2.0.3
